[package]
name = "yt-dlp"
edition = "2021"
version = "1.1.4"

authors = ["boul2gom <contact@boul2gom.fr>"]
description = "âš™ï¸ A Rust library (with auto dependencies downloading) for yt-dlp ğŸ¬ï¸"

license = "GPL-3.0"
readme = "README.md"
documentation = "https://docs.rs/yt-dlp"
homepage = "https://github.com/boul2gom/yt-dlp"
repository = "https://github.com/boul2gom/yt-dlp"

categories = ["api-bindings", "asynchronous", "development-tools"]
keywords = ["youtube", "yt-dlp", "async", "downloader"]

[workspace.metadata.release]
shared-version = true
tag-message = "ğŸ”– v{{version}}"
pre-release-commit-message = "ğŸš§ v{{version}}"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = { version = "1.41.0", features = ["rt-multi-thread", "macros", "fs", "time", "process"] }
reqwest = { version = "0.12.9", features = ["json", "stream"] }
futures-util = "0.3.31"

serde = { version = "1.0.214", features = ["derive"] }
serde_json = "1.0.132"

derive_more = { version = "1.0.0", features = ["display"] }
thiserror = "1.0.66"

ordered-float = "4.4.0"
flate2 = "1.0.34"
tar = "0.4.42"
zip = "2.2.0"
xz2 = "0.1.7"

[dev-dependencies]
lazy_static = "1.5.0"
