name: Github CI - Automatic biweekly release

on:
  schedule:
    - cron: '0 0 1,15 * *'
  workflow_dispatch:

permissions:
  contents: read

jobs:
  create_release:
    name: ğŸ”– Create a new release
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: ğŸ“ Check out the repository
        uses: actions/checkout@v4.2.2

      - name: ğŸ“¦ Cache Rust toolchain
        uses: Swatinem/rust-cache@v2
        with:
          prefix-key: rust-toolchain-

      - name: ğŸ› ï¸ Set up Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable

      - name: ğŸ“Œ Install cargo-release
        run: cargo install cargo-release

      - name: ğŸªª Set up Git identity
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

      - name: ğŸš€ Create a new patch release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
        run: cargo release patch --execute --no-confirm

      - name: ğŸ” Get new version
        id: get_version
        run: echo "version=$(cargo metadata --no-deps --format-version 1 | jq -r '.packages[0].version')" >> $GITHUB_ENV

      - name: ğŸ“ Create GitHub Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v${{ env.version }}
          release_name: ğŸ”– v${{ env.version }}
          draft: false
          prerelease: false